### ISSUE TITLE
org.mitre.stix.stix_1.STIXPackage.fromXMLString parsing XML to String issue

### ISSUE THREAD

**Issue by ai2017** [STIXProject/java-stix#9]
I am using stix 1.2.0.2 with the dependency
compile 'org.mitre:stix:1.2.0.2' from
https://github.com/STIXProject/java-stix but I see the following error
when I try to convert a XML file to String calling the API . I am
using java version "1.7.0_76" Java(TM) SE Runtime Environment (build
1.7.0_76-b13) to compile.  The artifact is deployed in Oracle Weblogic Server 12.1.3 but works from command line invoking main class from the jar

 org.mitre.stix.stix_1.STIXPackage.fromXMLString(STIXPackage.java:1087)

java.lang.ClassCastException:
com.sun.org.apache.xerces.internal.dom.DocumentImpl cannot be cast to
org.w3c.dom.Element
        at org.eclipse.persistence.internal.oxm.XMLCompositeObjectMappingNodeValue.endSelfNodeValue(XMLCompositeObjectMappingNodeValue.java:431)
        at org.eclipse.persistence.oxm.record.UnmarshalRecord.endDocument(UnmarshalRecord.java:597)
        at org.eclipse.persistence.oxm.record.UnmarshalRecord.endDocument(UnmarshalRecord.java:587)
        at org.eclipse.persistence.oxm.record.UnmarshalRecord.endElement(UnmarshalRecord.java:1038)
        at org.eclipse.persistence.internal.oxm.record.XMLReader$ValidatingContentHandler.endElement(XMLReader.java:438)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.endElement(AbstractSAXParser.java:609)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1782)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2973)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:117)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:648)
        at weblogic.xml.jaxp.WebLogicXMLReader.parse(WebLogicXMLReader.java:133)
        at weblogic.xml.jaxp.RegistryXMLReader.parse(RegistryXMLReader.java:173)
        at org.eclipse.persistence.internal.oxm.record.XMLReader.parse(XMLReader.java:222)
        at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:883)
        at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:372)
        at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:613)
        at org.eclipse.persistence.internal.oxm.record.SAXUnmarshaller.unmarshal(SAXUnmarshaller.java:649)
        at org.eclipse.persistence.oxm.XMLUnmarshaller.unmarshal(XMLUnmarshaller.java:588)
        at org.eclipse.persistence.jaxb.JAXBUnmarshaller.unmarshal(JAXBUnmarshaller.java:285)
        at org.mitre.stix.stix_1.STIXPackage.fromXMLString(STIXPackage.java:1087)

Thanks,
Sunil

**Comment by nemonik** [comment]
So your code doesn't work when deploy to an Oracle Weblogic Server 12.1.3, but works from command line invoking main class from the jar.  You have a dependency issue.  I would suggest you use something like

```
import java.net.URL;
import java.net.URLClassLoader;

ClassLoader cl = ClassLoader.getSystemClassLoader();
URL[] urls = ((URLClassLoader)cl).getURLs();

for (URL url: urls) {
    System.out.println(url.getFile());
}
```

And inspect what dependencies you are pulling in, and work from there.

You may have to utilize your own class loader to isolate yourself from WebLogic.  Take a look at the java-stix-validator project for an example of how to do that.

Also read this https://docs.oracle.com/cd/E24329_01/web.1211/e24368/classloading.htm or Google for similar aritcles.  I would suggest looking at the "Using the Classloader Analysis Tool (CAT)" section.

Your issue isn't with java-stix, so I am going to close this ticket.

**Comment by nemonik** [comment]
If you are still having the problem you've described please provide two
simple projects each with automated builds (e.g., Bradley, Maven) one
demonstrating the issue with v.1.2.0.2 and the other demonstrating the
success with v.1.2 that can be executed from the command-line.

-Michael

**Comment by ai2017** [comment]
Thanks Michael for the reply. This issue is resolved by specifying the
required packages to load for Oracle Weblogic Server.
